### ISSUE TITLE
Boundary conditions test fails randomly

### ISSUE THREAD

**Issue by jondea** [jondea/MultipleScattering.jl#1]
The boundary conditions test uses randomly generated particles, and this sometimes cause the test to fail ([example](https://travis-ci.org/jondea/MultipleScattering.jl/jobs/299170908)). We need to make the test more permissive (but still strong), or alternatively use a seed which is known to pass.

**Comment by arturgower** [comment]
I think choosing a seed makes more sense. Then we can still be rather stringent on the boundary test.

**Comment by jondea** [comment]
I agree we should choose a seed eventually, but it worries me slightly that it fails so often. Do you know where it is failing?

**Comment by jondea** [comment]
Displacement jumps are suppose to be strictly decreasing in k, but here's an example where it ever so slightly isn't:
0.00013567, 0.000133472

Pretty minimal tbh.

**Comment by arturgower** [comment]
I've solved this by using one specific seed to generate the random particles. I forgot to tag this issue in my commit...
