### ISSUE TITLE
Change the type of `FrequencySimulationResult.ω` from `RowVector` in to just `Vector`?

### ISSUE THREAD

**Issue by arturgower** [jondea/MultipleScattering.jl#24]
As of Julia 1.0, `RowVector` is no longer a thing. See [this issue](https://github.com/JuliaLang/julia/issues/20978). 

Instead there is a type `Transpose`, `Adjoint`, or just `Array{2}`. All in all, I think there is plenty of room for confusion now, and the intuitive idea of having a "lying down" vector is lost. So I suggest just using `Vector` for the type `FrequencySimulationResult.ω`.

**Comment by jondea** [comment]
I agree, also thanks for working on moving to Julia 1.0!
