### ISSUE TITLE
plot fields inside particles

### ISSUE THREAD

**Issue by arturgower** [jondea/MultipleScattering.jl#6]
The package already calculates [the field inside](https://github.com/jondea/MultipleScattering.jl/blob/master/src/response.jl#L21) the particles. So we should plot this field! Only graphical issue is that if the scatterers are impenetrable, then the fields inside [will return 0 ](https://github.com/jondea/MultipleScattering.jl/blob/master/src/response.jl#L46), which could make visualisation tricky. 

I suggest we draw a grey outline around the particles, so that we can continue to see them. 

Adding this feature will allow to simulate waveguides!

**Comment by jondea** [comment]
Zero shouldn't be a problem at all, try just removing the fill and see what happens. If it is zero then it should just be white inside

**Comment by arturgower** [comment]
I made the fillalpha inversely proportional to soundspeed*density of the particle. That is, the stronger the scattering, the more opaque the particle. Looks great!

**Comment by jondea** [comment]
Does that obscure the field inside the particle?

**Comment by arturgower** [comment]
Not really, as the field turns white inside the particles when soundspeed*density becomes very low. Though I also think we can just remove this fill if we find that it does get in the way.

**Comment by jondea** [comment]
Are you saying that the field inside the particle is usually negligible when the grey is significant? Wouldn't it be less confusing just to have the outline of the particle and just show field?

**Comment by arturgower** [comment]
Yeah sure, the fill might confuse. Feel free to remove it =]
