### ISSUE TITLE
Rename Moments type

### ISSUE THREAD

**Issue by jondea** [jondea/MultipleScattering.jl#7]
It's odd that Moment has a subtype which is called moments. It would make more sense to call it label+moments or moments with metadata. Another idea would be to borrow the word from [Summary Statistics](https://en.wikipedia.org/wiki/Summary_statistics) and call it a ModelSummary.

**Comment by arturgower** [comment]
How about WaveMoments for the name of the type? That suggests it has moments + metadata

**Comment by jondea** [comment]
But we haven't used the word wave anywhere else, it would be odd to only use it here in relation to FrequencyModels and TimeModels

**Comment by arturgower** [comment]
I'm wondering if we shouldn't rename those too. I mean "Model" is very vague. What if instead we used FrequencyMST, TimeMST and MomentsMST ? With MST meaning Multiple ScaTtering? That way we only have one keyword MST throughout our package, and it avoids any future conflict with other packages. I mean the word TimeModel could be used in so many other circumstances.

**Comment by jondea** [comment]
I agree, although I'm not sure I like MST, especially given that our package is called MultipleScattering so their full names would be MultipleScattering.FrequencyMST and MultipleScattering.TimeMST. I wouldn't worry about name conflicts, because if they exist then people can use the full names. I think clarity and meaning is more important.

**Comment by arturgower** [comment]
Then how about replacing MST with just Wave, or Scattering? So FrequencyWave, TimeWave, MomentsWave?

**Comment by arturgower** [comment]
We decided on the names for the types: FrequencySimulation and TimeSimulation, as it makes it clear that these are objects with all the information necessary to do a whole simulation. For the moments type we choose StatisticalMoments to clearly differentiate it from other definitions of moments.
