### ISSUE TITLE
Frequency or wavenumber

### ISSUE THREAD

**Issue by jondea** [jondea/MultipleScattering.jl#8]
We should really use one of frequency or wavenumber almost everywhere. Although wavenumber is important, I suspect frequency (angular or not?) is more natural to use. We already call the main type a FrequencyModel, even though we parameterise by wavenumber. Given that wavenumber (in the medium) is still important to the validity, we could always print the wavenumber range when calculating the model. What do you think?

**Comment by arturgower** [comment]
Yes I think it's more natural to use angular frequency everywhere. Perhaps instead of printing wavenumber when loading FrequencyModel,we could print the maximum ka (wavenumber times radius)? That's physically the most relevant non-dimensional quantity.

**Comment by jondea** [comment]
I think I agree. Good point, is minimum ka also relevant? Do you know of any literature on it?

Similarly, would it be useful to print the minimum separation distance? (I think you said that it has some numerical significance)

**Comment by arturgower** [comment]
Yes, the smaller the ratio between the separation distance and the radius, the more hankel functions are needed. I found not found a good reference yet. The best way to study this error is to take two cylinders and study how the error on the boundary (or better yet far-field scattering) changes when the cylinders get closer to each other.

**Comment by jondea** [comment]
Sure, might make for an interesting example

**Comment by jondea** [comment]
Version 0.2 will use angular frequency everywhere, so that wavenumber is always derived when required from the angular frequency (ω) and wave speed (c). I think version 0.1 will just stay as it is, even if it is a bit inconsistent.
